apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-storage
  namespace: securetransfer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  # storageClassName: gp2  # ggf. anpassen
