apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: securetransfer
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      # app-sa hat anyuid SCC → postgres:17-alpine kann als UID 70 laufen
      serviceAccountName: app-sa
      containers:
        - name: postgres
          image: postgres:17-alpine
          env:
            - name: POSTGRES_USER
              value: dap
            - name: POSTGRES_DB
              value: dap
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: securetransfer-secrets
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "dap"]
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "dap"]
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
